import express from "express";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";

// ✅ Fix for ES Modules (__dirname is not available by default)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// ✅ Serve static files (make sure path is correct)
app.use("/images", express.static(path.join(__dirname, "public", "images")));

// ✅ Sample route for food data
app.get("/", (req, res) => {
  const foodData = [
    {
      id: "1 ",
      name: "Boilded Egg",
      price: 10,
      text: "Soft and delicious boiled eggs to start your day healthy.",
      image: "/images/boildedegg.png",
      type: "breakfast",
    },
    {
      id: " 2",
      name: "RAMEN",
      price: 25,
      text: "Hot ramen noodles with spicy broth and boiled egg.",
      image: "/images/ramen.png",
      type: "lunch",
    },
    {
      id: " 3",
      name: "GRILLED CHICKEN",
      price: 45,
      text: "Juicy grilled chicken with smoky flavor.",
      image: "/images/grilledchiken.png",
      type: "dinner",
    },
    {
      id: " 4",
      name: "CAKE",
      price: 18,
      text: "Sweet and fluffy cake perfect for breakfast or dessert.",
      image: "/images/cake.png",
      type: "breakfast",
    },
    {
      id: " 5",
      name: "BURGER",
      price: 23,
      text: "Juicy chicken burger with lettuce and cheese.",
      image: "/images/burger.png",
      type: "lunch",
    },
    {
      id: " 6",
      name: "PANCAKE",
      price: 25,
      text: "Soft pancakes with maple syrup and butter.",
      image: "/images/pancake.png",
      type: "dinner",
    },

    {
      id: " 7",
      name: "Sandwich",
      price: 12,
      text: "Crispy sandwich with veggies and cheese.",
      image: "/images/sandwitch.png",
      type: "breakfast",
    },
    {
      id: " 8",
      name: "Pasta",
      price: 27,
      text: "Creamy Alfredo pasta with mushrooms.",
      image: "/images/pasta.png",
      type: "lunch",
    },
    {
      id: " 9",
      name: "Steak",
      price: 60,
      text: "Tender steak cooked to perfection.",
      image: "/images/steak.png",
      type: "dinner",
    },
    {
      id: " 10",
      name: "Omelette",
      price: 14,
      text: "Fluffy omelette with onions and cheese.",
      image: "/images/omelette.png",
      type: "breakfast",
    },
    {
      id: " 11",
      name: "Pizza",
      price: 35,
      text: "Cheesy pizza with pepperoni and veggies.",
      image: "/images/pizza.png",
      type: "lunch",
    },
    {
      id: " 12",
      name: "Fish Curry",
      price: 50,
      text: "Spicy fish curry cooked in coconut gravy.",
      image: "/images/fish-curry.png",
      type: "dinner",
    },
    {
      id: " 13",
      name: "French Toast",
      price: 20,
      text: "Golden fried toast with cinnamon flavor.",
      image: "/images/toast.png",
      type: "breakfast",
    },
    {
      id: " 14",
      name: "Chicken Fried Rice",
      price: 40,
      text: "Fried rice with shredded chicken and veggies.",
      image: "/images/friedrice.png",
      type: "lunch",
    },
    {
      id: "15 ",
      name: "Mutton Kebab",
      price: 55,
      text: "Tender spiced mutton kebabs.",
      image: "/images/kebab.png",
      type: "dinner",
    },
    {
      id: "16 ",
      name: "Waffles",
      price: 22,
      text: "Crispy waffles with syrup and cream.",
      image: "/images/waffles.png",
      type: "breakfast",
    },
    {
      id: "17 ",
      name: "Noodles",
      price: 28,
      text: "Stir-fried noodles with soy sauce and veggies.",
      image: "/images/noodles.png",
      type: "lunch",
    },
    {
      id: "18 ",
      name: "Beef Curry",
      price: 65,
      text: "Rich and spicy beef curry.",
      image: "/images/beef.png",
      type: "dinner",
    },
    {
      id: "19 ",
      name: "Cereal Bowl",
      price: 8,
      text: "Healthy cereal with milk and fruits.",
      image: "/images/cereal.png",
      type: "breakfast",
    },
    {
      id: "20 ",
      name: "Sushi",
      price: 55,
      text: "Fresh sushi rolls with salmon and rice.",
      image: "/images/sushi.png",
      type: "lunch",
    },
    {
      id: " 21",
      name: "Roasted Lamb",
      price: 75,
      text: "Perfectly roasted lamb with herbs.",
      image: "/images/lamb.png",
      type: "dinner",
    },
    {
      id: " 22",
      name: "Avocado Toast",
      price: 18,
      text: "Toasted bread with mashed avocado.",
      image: "/images/avocado.png",
      type: "breakfast",
    },
    {
      id: " 23",
      name: "Tacos",
      price: 30,
      text: "Mexican tacos with beef and salsa.",
      image: "/images/tacos.png",
      type: "lunch",
    },
    {
      id: " 24",
      name: "Butter Chicken",
      price: 50,
      text: "Creamy butter chicken with naan.",
      image: "/images/butterchicken.png",
      type: "dinner",
    },
    {
      id: " 25",
      name: "Smoothie Bowl",
      price: 15,
      text: "Fruit smoothie topped with granola.",
      image: "/images/smoothie.png",
      type: "breakfast",
    },
    {
      id: " 26",
      name: "Burrito",
      price: 32,
      text: "Stuffed burrito with rice, beans, and meat.",
      image: "/images/burrito.png",
      type: "lunch",
    },
    {
      id: " 27",
      name: "BBQ Ribs",
      price: 70,
      text: "Smoky BBQ ribs with sauce.",
      image: "/images/ribs.png",
      type: "dinner",
    },
    {
      id: " 28",
      name: "Muffin",
      price: 10,
      text: "Soft chocolate chip muffin.",
      image: "/images/muffin.png",
      type: "breakfast",
    },
    {
      id: " 29",
      name: "Wrap",
      price: 24,
      text: "Chicken wrap with veggies.",
      image: "/images/wrap.png",
      type: "lunch",
    },
    {
      id: " 30",
      name: "Lasagna",
      price: 55,
      text: "Baked lasagna with cheese layers.",
      image: "/images/lasagna.png",
      type: "dinner",
    },
    {
      id: " 31",
      name: "Fruit Salad",
      price: 12,
      text: "Fresh seasonal fruits.",
      image: "/images/fruits.png",
      type: "breakfast",
    },
    {
      id: " 32",
      name: "Quesadilla",
      price: 26,
      text: "Mexican quesadilla with cheese.",
      image: "/images/quesadilla.png",
      type: "lunch",
    },
    {
      id: " 33",
      name: "Biryani",
      price: 50,
      text: "Spicy chicken biryani.",
      image: "/images/biryani.png",
      type: "dinner",
    },
    {
      id: " 34",
      name: "Donut",
      price: 9,
      text: "Glazed donut with chocolate.",
      image: "/images/donut.png",
      type: "breakfast",
    },
    {
      id: " 35",
      name: "Hot Dog",
      price: 20,
      text: "Classic hot dog with mustard.",
      image: "/images/hotdog.png",
      type: "lunch",
    },
    {
      id: " 36",
      name: "Prawn Curry",
      price: 60,
      text: "Shrimp cooked in spicy sauce.",
      image: "/images/prawn.png",
      type: "dinner",
    },
    {
      id: " 37",
      name: "Bagel",
      price: 14,
      text: "Toasted bagel with cream cheese.",
      image: "/images/bagel.png",
      type: "breakfast",
    },
    {
      id: "38 ",
      name: "Curry Rice",
      price: 33,
      text: "Rice served with thick curry.",
      image: "/images/curry.png",
      type: "lunch",
    },
    {
      id: "39 ",
      name: "Roast Chicken",
      price: 58,
      text: "Whole roasted chicken with gravy.",
      image: "/images/roastchicken.png",
      type: "dinner",
    },
    {
      id: "40 ",
      name: "Croissant",
      price: 11,
      text: "Flaky croissant with butter.",
      image: "/images/croissant.png",
      type: "breakfast",
    },
    {
      id: "41 ",
      name: "Shawarma",
      price: 28,
      text: "Chicken shawarma wrap.",
      image: "/images/shawarma.png",
      type: "lunch",
    },
    {
      id: "42 ",
      name: "Beef Steak",
      price: 68,
      text: "Thick-cut beef steak grilled perfectly.",
      image: "/images/beefsteak.png",
      type: "dinner",
    },
    {
      id: "43 ",
      name: "Paratha",
      price: 8,
      text: "Crispy layered paratha.",
      image: "/images/paratha.png",
      type: "breakfast",
    },
    {
      id: "44 ",
      name: "Chow Mein",
      price: 29,
      text: "Chinese-style chow mein.",
      image: "/images/chowmein.png",
      type: "lunch",
    },
    {
      id: " 45",
      name: "Duck Roast",
      price: 72,
      text: "Crispy roasted duck with sauce.",
      image: "/images/duck.png",
      type: "dinner",
    },
    {
      id: " 46",
      name: "Idli",
      price: 10,
      text: "South Indian steamed idlis.",
      image: "/images/idli.png",
      type: "breakfast",
    },
    {
      id: " 47",
      name: "Falafel",
      price: 26,
      text: "Middle Eastern falafel balls.",
      image: "/images/falafel.png",
      type: "lunch",
    },
    {
      id: " 48",
      name: "Lamb Curry",
      price: 65,
      text: "Spiced lamb curry with herbs.",
      image: "/images/lambcurry.png",
      type: "dinner",
    },
    {
      id: " 49",
      name: "Dosa",
      price: 15,
      text: "Crispy dosa with chutney.",
      image: "/images/dosa.png",
      type: "breakfast",
    },
    {
      id: " 50",
      name: "Fried Chicken",
      price: 35,
      text: "Crispy golden fried chicken.",
      image: "/images/friedchicken.png",
      type: "lunch",
    },
    {
      id: " 51",
      name: "Shrimp Pasta",
      price: 50,
      text: "Creamy pasta with shrimp.",
      image: "/images/shrimppasta.png",
      type: "dinner",
    },
    {
      id: " 52",
      name: "Toast & Jam",
      price: 9,
      text: "Toasted bread with strawberry jam.",
      image: "/images/toastjam.png",
      type: "breakfast",
    },
    {
      id: " 53",
      name: "Veg Burger",
      price: 22,
      text: "Vegetable burger with cheese slice.",
      image: "/images/vegburger.png",
      type: "lunch",
    },
    {
      id: " 54",
      name: "Beef Stroganoff",
      price: 62,
      text: "Beef strips in creamy sauce.",
      image: "/images/beefstroganoff.png",
      type: "dinner",
    },
    {
      id: " 55",
      name: "Granola",
      price: 13,
      text: "Granola with yogurt and honey.",
      image: "/images/granola.png",
      type: "breakfast",
    },
    {
      id: " 56",
      name: "Paneer Tikka",
      price: 32,
      text: "Indian-style grilled paneer cubes.",
      image: "/images/paneer.png",
      type: "lunch",
    },
    {
      id: " 57",
      name: "Goat Curry",
      price: 70,
      text: "Rich and spicy goat curry.",
      image: "/images/goat.png",
      type: "dinner",
    },
    {
      id: " 58",
      name: "Scrambled Eggs",
      price: 11,
      text: "Light scrambled eggs with butter.",
      image: "/images/scrambled.png",
      type: "breakfast",
    },
    {
      id: " 59",
      name: "Fajitas",
      price: 35,
      text: "Sizzling chicken fajitas.",
      image: "/images/fajitas.png",
      type: "lunch",
    },
    {
      id: " 60",
      name: "Meatballs",
      price: 55,
      text: "Juicy meatballs in tomato sauce.",
      image: "/images/meatballs.png",
      type: "dinner",
    },
    {
      id: " 61",
      name: "Toast & Butter",
      price: 7,
      text: "Simple toast with butter spread.",
      image: "/images/toastbutter.png",
      type: "breakfast",
    },
    {
      id: " 62",
      name: "Tortilla",
      price: 27,
      text: "Stuffed tortilla wrap.",
      image: "/images/tortilla.png",
      type: "lunch",
    },
    {
      id: " 63",
      name: "Seafood Platter",
      price: 80,
      text: "Mix of seafood delicacies.",
      image: "/images/seafood.png",
      type: "dinner",
    },
    {
      id: " 64",
      name: "Cupcake",
      price: 10,
      text: "Mini cupcakes with icing.",
      image: "/images/cupcake.png",
      type: "breakfast",
    },
    {
      id: "65 ",
      name: "Rice Bowl",
      price: 34,
      text: "Rice with mixed veggies.",
      image: "/images/ricebowl.png",
      type: "lunch",
    },
    {
      id: "66 ",
      name: "Roast Beef",
      price: 68,
      text: "Slow-cooked roast beef.",
      image: "/images/roastbeef.png",
      type: "dinner",
    },
    {
      id: "67 ",
      name: "Egg Roll",
      price: 16,
      text: "Egg rolls filled with veggies.",
      image: "/images/eggroll.png",
      type: "breakfast",
    },
    {
      id: "68 ",
      name: "Grilled Sandwich",
      price: 20,
      text: "Cheese grilled sandwich.",
      image: "/images/grilledsandwich.png",
      type: "lunch",
    },
    {
      id: "69 ",
      name: "Mutton Roast",
      price: 72,
      text: "Roasted mutton leg.",
      image: "/images/muttonroast.png",
      type: "dinner",
    },
    {
      id: "70 ",
      name: "Banana Bread",
      price: 14,
      text: "Moist banana bread slice.",
      image: "/images/bananabread.png",
      type: "breakfast",
    },
    {
      id: "71 ",
      name: "Fried Rice",
      price: 36,
      text: "Chinese fried rice with egg.",
      image: "/images/friedrice2.png",
      type: "lunch",
    },
    {
      id: "72 ",
      name: "Grilled Salmon",
      price: 66,
      text: "Salmon fillet grilled in butter.",
      image: "/images/salmon.png",
      type: "dinner",
    },
    {
      id: "73 ",
      name: "Porridge",
      price: 9,
      text: "Warm oatmeal with honey.",
      image: "/images/porridge.png",
      type: "breakfast",
    },
    {
      id: "74 ",
      name: "Veg Noodles",
      price: 28,
      text: "Stir-fried noodles with cabbage.",
      image: "/images/vegnoodles.png",
      type: "lunch",
    },
    {
      id: "75",
      name: "Turkey Roast",
      price: 74,
      text: "Thanksgiving-style turkey roast.",
      image: "/images/turkey.png",
      type: "dinner",
    },
    {
      id: "76 ",
      name: "Chia Pudding",
      price: 17,
      text: "Healthy chia seed pudding.",
      image: "/images/chia.png",
      type: "breakfast",
    },
    {
      id: "77 ",
      name: "Pita Bread",
      price: 24,
      text: "Soft pita bread with hummus.",
      image: "/images/pita.png",
      type: "lunch",
    },
    {
      id: "78 ",
      name: "Spaghetti",
      price: 55,
      text: "Italian spaghetti with sauce.",
      image: "/images/spaghetti.png",
      type: "dinner",
    },
    {
      id: "79 ",
      name: "Pancake Stack",
      price: 26,
      text: "Stacked pancakes with syrup.",
      image: "/images/pancakestack.png",
      type: "breakfast",
    },
    {
      id: "80 ",
      name: "Veg Wrap",
      price: 22,
      text: "Vegetable wrap with sauce.",
      image: "/images/vegwrap.png",
      type: "lunch",
    },
    {
      id: "81 ",
      name: "Grilled Fish",
      price: 60,
      text: "Fish fillet grilled in olive oil.",
      image: "/images/grilledfish.png",
      type: "dinner",
    },
    {
      id: "82 ",
      name: "Oatmeal",
      price: 10,
      text: "Warm oatmeal with banana.",
      image: "/images/oatmeal.png",
      type: "breakfast",
    },
    {
      id: "83 ",
      name: "Curry Puff",
      price: 25,
      text: "Spicy curry puff pastry.",
      image: "/images/currypuff.png",
      type: "lunch",
    },
    {
      id: "84 ",
      name: "Tandoori Chicken",
      price: 62,
      text: "Spicy tandoori roasted chicken.",
      image: "/images/tandoori.png",
      type: "dinner",
    },
    {
      id: "85 ",
      name: "Crepe",
      price: 18,
      text: "French crepe with chocolate filling.",
      image: "/images/crepe.png",
      type: "breakfast",
    },
    {
      id: "86 ",
      name: "Kathi Roll",
      price: 29,
      text: "Indian-style wrap with filling.",
      image: "/images/kathiroll.png",
      type: "lunch",
    },
    {
      id: "87 ",
      name: "Lobster Tail",
      price: 90,
      text: "Luxury lobster tail dish.",
      image: "/images/lobster.png",
      type: "dinner",
    },
    {
      id: "88 ",
      name: "Egg Muffin",
      price: 13,
      text: "Egg muffin with spinach.",
      image: "/images/eggmuffin.png",
      type: "breakfast",
    },
    {
      id: "89 ",
      name: "Couscous Salad",
      price: 31,
      text: "Healthy couscous with veggies.",
      image: "/images/couscous.png",
      type: "lunch",
    },
    {
      id: "90 ",
      name: "Grilled Prawns",
      price: 67,
      text: "Prawns grilled in garlic butter.",
      image: "/images/grilledprawns.png",
      type: "dinner",
    },
    {
      id: "91 ",
      name: "Protein Shake",
      price: 16,
      text: "Banana and peanut protein shake.",
      image: "/images/protein.png",
      type: "breakfast",
    },
    {
      id: "92 ",
      name: "Veg Pizza",
      price: 34,
      text: "Vegetarian pizza with olives.",
      image: "/images/vegpizza.png",
      type: "lunch",
    },
    {
      id: "93 ",
      name: "Duck Curry",
      price: 72,
      text: "Spicy duck curry with herbs.",
      image: "/images/duckcurry.png",
      type: "dinner",
    },
    {
      id: "94 ",
      name: "Fruit Yogurt",
      price: 12,
      text: "Yogurt mixed with berries.",
      image: "/images/yogurt.png",
      type: "breakfast",
    },
    {
      id: "95 ",
      name: "Chicken Nuggets",
      price: 26,
      text: "Crispy golden chicken nuggets.",
      image: "/images/nuggets.png",
      type: "lunch",
    },
    {
      id: "96 ",
      name: "Prawn Masala",
      price: 64,
      text: "Indian prawn masala curry.",
      image: "/images/prawnmasala.png",
      type: "dinner",
    },
    {
      id: "97 ",
      name: "Egg Paratha",
      price: 14,
      text: "Stuffed paratha with egg.",
      image: "/images/eggparatha.png",
      type: "breakfast",
    },
    {
      id: "98 ",
      name: "Chicken Shawarma",
      price: 30,
      text: "Chicken shawarma wrap with garlic sauce.",
      image: "/images/chickenshawarma.png",
      type: "lunch",
    },
    {
      id: "99 ",
      name: "Mutton Handi",
      price: 68,
      text: "Rich handi-style mutton curry.",
      image: "/images/muttonhandi.png",
      type: "dinner",
    },
  ];
res.json(foodData.map(item => ({
  ...item,
  id: item.id.trim()
})));
});

const PORT = 9000;
app.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
});
